config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resource :declaring, only: [:new, :create]

  resources :city_council, path: 'rada', only: [:show]
  resources :position, path: 'posada', only: [:show]

  get '/add-disclosure', to: 'declarings#new'

  get '/general-income/family', to: 'general_income#family'
  get '/general-income/personal', to: 'general_income#personal'

  get '/public-asset-disclosure/learn-more', to: 'pages#disclosure_learn'
  get '/control-disclosure-information/learn-more', to: 'pages#control_disclosure'

  get '/family-general-income', to: 'main#family_general_income'
  get '/personal-general-income', to: 'main#personal_general_income'

  root 'main#index'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @disclosures = disclosures.oder_by_personal_general_income

    @max_income = (@disclosures.map {|disclosure| disclosure.general_income_value}).max
    @max_income = 1 if @max_income == 0
  end

  def family_general_income
    @disclosures = disclosures.oder_by_family_general_income
    income_values = @disclosures.map {|disclosure| disclosure.family_general_income_value}

    @max_income = income_values.max
    @max_income = 1 if @max_income == 0
    respond_to do |format|
      format.js { render partial: 'family_general_income'}
    end
  end

  def personal_general_income
    @disclosures = disclosures.oder_by_personal_general_income
    income_values = @disclosures.map {|disclosure| disclosure.general_income_value}

    @max_income =  income_values.max
    @max_income = 1 if @max_income == 0
    respond_to do |format|
      format.js { render partial: 'personal_general_income'}
    end
  end

private

  def disclosures
    FinanceDisclosure.includes(official: [:person, :position, :city_council])
  end
end

app/helpers/main_helper.rb
module MainHelper
  include PersonHelper
  BOX_WIDTH_100 = 200

  def box_width(disclosure, income)
    (BOX_WIDTH_100*disclosure.send(income))/@max_income
  end

  def income(disclosure, income)
    number_with_delimiter(disclosure.send(income), delimiter: ' ')
  end

  def deklarant_surname(disclosure)
    surname(disclosure.official_name)
  end

  def deklarant_imya_otchestvo(disclosure)
    imya_otchestvo(disclosure.official_name)
  end

  def posada(disclosure)
    disclosure.official_position
  end

  def city_council(disclosure)
    disclosure.city_council
  end
end

app/views/main/_disclosure.haml
%article.disclosure
  .general-income-value
    - if income_value.eql?(:general_income_value)
      .box{data:{value: box_width(disclosure, income_value)}}
    - else
      .box.family{data:{value: box_width(disclosure, income_value)}}
    - if income_value.eql?(:general_income_value)
      .box-second{data:{value: box_width(disclosure, second_income_value)}}
  .general-income
    = income(disclosure, income_value)
  .person
    %a{href:'#'}
      = deklarant_surname(disclosure)
      %br
      = deklarant_imya_otchestvo(disclosure)
  .position
    = link_to posada(disclosure), position_path(posada(disclosure))
  .city-council
    = link_to city_council(disclosure), city_council_path(city_council(disclosure))

app/views/main/_disclosures.haml
- disclosures.each do |disclosure|
  - if income_value.eql?(:family_general_income_value)
    - unless disclosure.family_general_income_value.eql?(0)
      = render partial: 'disclosure', locals: {disclosure: disclosure, income_value: income_value, second_income_value: second_income_value}
  - if income_value.eql?(:general_income_value)
    = render partial: 'disclosure', locals: {disclosure: disclosure, income_value: income_value, second_income_value: second_income_value}

app/views/main/_family_general_income.js.erb
$("#family_income_button").parent('li').addClass('active');
$("#personal_income_button").parent('li').removeClass('active');
$("#disclosures").html("<%= escape_javascript(render partial: 'main/disclosures',
locals: { disclosures: @disclosures, income_value: :family_general_income_value, second_income_value: :general_income_value}) %>");

app/views/main/_personal_general_income.js.erb
$("#family_income_button").parent('li').removeClass('active');
$("#personal_income_button").parent('li').addClass('active');
$("#disclosures").html("<%= escape_javascript(render partial: 'main/disclosures',
locals: { disclosures: @disclosures, income_value: :general_income_value, second_income_value: :family_general_income_value}) %>");

app/views/main/index.haml
%section.promo-menu
  %header
    %h2
      Открытые декларации всему голова
  %nav.promo-nav
    .block
      .income
        = link_to 'Общий доход', root_path, class: 'income'
      .asset
        = link_to 'Майно', root_path, class: 'income'
      .by_city
        = link_to 'Горсовет', root_path, class: 'income'

%section.d3chart
%svg#graph


%section.disclosures-menu
  %header
    %h2.disclosures-header
      Общая сумма дохода
  %nav.income-menu
    %ul
      %li.active
        = link_to 'Декларант', personal_general_income_path, remote: true, id: 'personal_income_button'
      %li
        = link_to 'Члены семьи', family_general_income_path, remote: true, id: 'family_income_button'

%section.disclosures#disclosures
  = render partial: 'main/disclosures', locals: { disclosures: @disclosures, income_value: :general_income_value, second_income_value: :family_general_income_value}

app/views/main/index.html.haml
%header.flex
  %h1
    Финансовые декларации
  .action
    .add_disclosure
      = link_to 'Добавить декларацию', disclosure_new_path, class: 'btn btn-default'

.container
  .row
    .cities.col-md-12
      - 15.times do
        .city
          .city_name
            Донецк
          .titles
            .item.golova
              .title
                Голова
              .income
                230.000 ₴
            - 2.times do
              .item
                .title
                  Заступник
                .income
                  230.000 ₴
      - 15.times do
        .city
          .city_name
            Донецк
          .titles
            .item.golova
              .title
                Голова
              .income
                230.000 ₴
            - 3.times do
              .item
                .title
                  Заступник
                .income
                  230.000 ₴