config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resource :declaring, only: [:new, :create]

  resources :city_council, path: 'rada', only: [:show]
  resources :position, path: 'posada', only: [:show]

  get '/add-disclosure', to: 'declarings#new'

  get '/general-income/family', to: 'general_income#family'
  get '/general-income/personal', to: 'general_income#personal'

  get '/public-asset-disclosure/learn-more', to: 'pages#disclosure_learn'
  get '/control-disclosure-information/learn-more', to: 'pages#control_disclosure'

  get '/family-general-income', to: 'main#family_general_income'
  get '/personal-general-income', to: 'main#personal_general_income'

  root 'main#index'
end

app/models/city_council.rb
# == Schema Information
#
# Table name: city_councils
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CityCouncil < ActiveRecord::Base
  has_many :officials

  validates :slug, uniqueness: true, presence: true
  validates_presence_of :name
  before_validation :generate_slug

  def to_s
    short_name
  end

  def to_param
    slug
  end

  def short_name
    name.split(' ')[0]
  end

  def generate_slug
    self.slug ||= name.to_slug.transliterate(:ukrainian).to_s.downcase.parameterize
  end

  def officials_disclosures
    officials.joins(:finance_disclosures)
  end
end

app/controllers/city_council_controller.rb
class CityCouncilController < ApplicationController
  before_filter :find_city_council, only: [:show]

  def show
    @disclosures = disclosures.oder_by_personal_general_income
    @max_general_income = (@disclosures.map {|disclosure| disclosure.general_income_value}).max
    @max_general_income = 1 if @max_general_income == 0
  end

private

  def find_city_council
    @city_council = CityCouncil.find_by_slug!(params[:id])
  end

  def disclosures
    FinanceDisclosure.includes(official: [:person, :position, :city_council]).where(:officials => {city_council_id: @city_council.id})
  end
end

app/helpers/city_council_helper.rb
module CityCouncilHelper
end

app/views/city_council/_disclosures.haml
%section.disclosures#disclosures
  - @disclosures.each do |disclosure|
    - value = (200*disclosure.general_income_value)/@max_general_income
    %article.disclosure
      .general-income-value
        .box{data:{value: value}}
      .general-income
        = disclosure.general_income_value
      .person
        %a{href:'#'}
          = disclosure.official_name
      .position
        = link_to posada(disclosure), position_path(posada(disclosure))

app/views/city_council/show.haml
%section.promo-menu
  %header
    %h2
      = @city_council.name

%section.disclosures-menu
  %header
    %h2.disclosures-header
      Общая сумма совокупного дохода
  %nav.income-menu
    %ul
      %li.active
        = link_to 'Декларант', general_income_personal_path, remote: true, id: 'personal_income_button'
      %li
        = link_to 'Члены семьи', general_income_family_path, remote: true, id: 'family_income_button'

= render 'city_council/disclosures'