config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resource :declaring, only: [:new, :create]

  resources :city_council, path: 'rada', only: [:show]
  resources :position, path: 'posada', only: [:show]

  get '/add-disclosure', to: 'declarings#new'

  get '/general-income/family', to: 'general_income#family'
  get '/general-income/personal', to: 'general_income#personal'

  get '/public-asset-disclosure/learn-more', to: 'pages#disclosure_learn'
  get '/control-disclosure-information/learn-more', to: 'pages#control_disclosure'

  get '/family-general-income', to: 'main#family_general_income'
  get '/personal-general-income', to: 'main#personal_general_income'

  root 'main#index'
end

app/models/declaring.rb
class Declaring
  include ActiveModel::Model

  attr_accessor :city_council_name, :person_name, :position_name, :year, :general_income_value, :family_general_income_value,
                :city_council, :person, :position, :official, :general_income, :family_general_income

  validates :city_council_name, presence: true
  validates :person_name, presence: true
  validates :position_name, presence: true
  validates :year, presence: true

  def declared
    if valid?
      create_city_council "#{@city_council_name} міська рада"
      create_person @person_name
      create_position @position_name

      create_official @city_council, @person, @position

      create_general_income @general_income_value
      create_family_general_income @family_general_income_value

      create_finance_disclosure official, @year, general_income, family_general_income
    end
  end

  private

  def create_city_council name
    @city_council = CityCouncil.where(name: name).first_or_create!
  end

  def create_person name
    @person = Person.where(full_name: name).first_or_create!
  end

  def create_position name
    @position = Position.where(full: name).first_or_create!
  end

  def create_official city_council, person, position
    @official = Official.where(person: person, position: position, city_council: city_council).first_or_create!
  end

  def create_general_income value
    @general_income = GeneralIncome.create!(amount_hryvna: value)
  end

  def create_family_general_income value
    @family_general_income = FamilyGeneralIncome.create!(amount_hryvna: value)
  end

  def create_finance_disclosure official, year, general_income, family_general_income
    FinanceDisclosure.create!(official: official, year: year, general_income: general_income, family_general_income: family_general_income)
  end
end

app/controllers/declarings_controller.rb
class DeclaringsController < ApplicationController
  respond_to :html

  def new
    @declaring = Declaring.new
  end

  def create
    @declaring = Declaring.new(declaring_params)
    @declaring.declared

    redirect_to add_disclosure_path
  end

  private

  def declaring_params
    params.require(:declaring).permit(:city_council_name, :person_name, :position_name, :year,
                                      :general_income_value, :family_general_income_value )
  end
end

app/views/declarings/new.html.haml
%section.add-disclosure-form
  = form_for @declaring, url: declaring_path do |f|
    .city_council
      = f.label :city_council_name, "Міська рада"
      = f.text_field :city_council_name, placeholder: nil, data: {autocomplete_source: CityCouncil.order(:name).map(&:short_name)}
    .year
      = f.label :year, "Рік"
      = f.text_field :year, type: 'number', data: {autocomplete_source: ''}
    .person
      = f.label :person_name, "Декларант"
      = f.text_field :person_name, placeholder: nil, data: {autocomplete_source: Person.order(:full_name).map(&:full_name)}
    .position
      = f.label :position_name, "Посада"
      = f.text_field :position_name, placeholder: nil, data: {autocomplete_source: Position.order(:full).map(&:full)}
    .general-income
      = f.label :general_income_value, "Общий доход декларанта"
      = f.text_field :general_income_value, value: 0, type: 'number'
    .family-general-income
      = f.label :family_general_income_value, "Общий доход семьи декларанта"
      = f.text_field :family_general_income_value, value: 0, type: 'number'

    = f.submit 'Add disclosure'