config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resource :declaring, only: [:new, :create]

  resources :city_council, path: 'rada', only: [:show]
  resources :position, path: 'posada', only: [:show]

  get '/add-disclosure', to: 'declarings#new'

  get '/general-income/family', to: 'general_income#family'
  get '/general-income/personal', to: 'general_income#personal'

  get '/public-asset-disclosure/learn-more', to: 'pages#disclosure_learn'
  get '/control-disclosure-information/learn-more', to: 'pages#control_disclosure'

  get '/family-general-income', to: 'main#family_general_income'
  get '/personal-general-income', to: 'main#personal_general_income'

  root 'main#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :disclosure_count

  def disclosure_count
    @disclosures_count ||= FinanceDisclosure.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.haml
%header.global-header
  .logo
    = link_to_unless_current 'ДК', root_path
  .block
    .citizens_link
      = link_to 'Для граждан', public_asset_disclosure_learn_more_path, class: 'citizens'
    .citizens_link
      = link_to 'Для муниципалитетов', control_disclosure_information_learn_more_path, class: 'local-government'
  .disclosures_count
    %span.value= @disclosures_count
    деклараций